version: '3.6'

services:
  elasticsearch:
    image: elasticsearch:$ELK_VERSION
    volumes:
      - type: bind
        source: ./docker/elasticsearch/config/elasticsearch.yml
        target: /usr/share/elasticsearch/config/elasticsearch.yml
        read_only: true
      - type: volume
        source: elasticsearch
        target: /usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      ELASTIC_PASSWORD: elastic
      # Use single node discovery in order to disable production mode and avoid bootstrap checks
      # see https://www.elastic.co/guide/en/elasticsearch/reference/current/bootstrap-checks.html
      discovery.type: single-node
    networks:
      - scentdb-elk

  logstash:
    image: logstash:$ELK_VERSION
    volumes:
      - type: bind
        source: ./docker/logstash/config/logstash.yml
        target: /usr/share/logstash/config/logstash.yml
        read_only: true
      - type: bind
        source: ./docker/logstash/pipeline
        target: /usr/share/logstash/pipeline
        read_only: true
    ports:
      - "5000:5000/tcp"
      - "5000:5000/udp"
      - "9600:9600"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - scentdb-elk
    depends_on:
      - elasticsearch

  kibana:
    image: kibana:$ELK_VERSION
    volumes:
      - type: bind
        source: ./docker/kibana/config/kibana.yml
        target: /usr/share/kibana/config/kibana.yml
        read_only: true
    ports:
      - "5601:5601"
    networks:
      - scentdb-elk
    depends_on:
      - elasticsearch

  scentdb:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: D:/Dev/project/scentdb/images # local directory where images are stored
        target: /app/images
    ports:
      - "8321:8321"
    networks:
      - scentdb-elk
    environment:
      SPRING_PROFILES_ACTIVE: h2
      LOGSTASH_HOST: logstash:5000
      LOGSTASH_ENABLED: "true"
      IMAGES_PATH: /app/images
    depends_on:
      - logstash

networks:
  scentdb-elk:
    driver: bridge

volumes:
  elasticsearch:
  images:


